name: Track Votes

on:
  issue_comment:
    types: [created, edited, deleted]
  issues:
    types: [opened, edited, closed]

permissions:
  contents: write
  issues: write

jobs:
  track-votes:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
    
    steps:
      - uses: ./.github/workflows/lua-setup.yaml
          
      - name: Process votes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: lua src/trackVotes.lua
